version: "3.8"
services:

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  registration-service:
        image: 'wexio/registration-service'
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/performers
          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=root

  production-service:
      image: 'wexio/production-service'
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8081:8081"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/productions
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
