apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod
      tier: backend
  template:
    metadata:
      labels:
        app: mysql-pod
        tier: backend
    spec:
      containers:
        - name: mysql-pod
          image: mysql:8.0
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-pod
      tier: backend
  template:
    metadata:
      labels:
        app: mail-pod
        tier: backend
    spec:
      containers:
        - name: mail-pod
          image: mailhog/mailhog:latest
          imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-pod
      tier: backend
  template:
    metadata:
      labels:
        app: production-pod
        tier: backend
    spec:
      containers:
        - name: production-pod
          image: wexio/production-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service.default:3306/productions?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: registration-service.url
              value: http://registration-service.default:8080
            - name: spring.mail.host
              value: mail-service.default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registration-pod
      tier: backend
  template:
    metadata:
      labels:
        app: registration-pod
        tier: backend
    spec:
      containers:
        - name: registration-pod
          image: wexio/registration-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service.default:3306/performers?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

---

apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-pod
    tier: backend
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
    - name: http
      protocol: TCP
      port: 8025
      targetPort: 8025
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-pod
    tier: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: production-service
spec:
  selector:
    app: production-pod
    tier: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  selector:
    app: registration-pod
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-oracle-front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stage-oracle-front-pod
      tier: frontend
  template:
    metadata:
      labels:
        app: stage-oracle-front-pod
        tier: frontend
    spec:
      containers:
        - name: stage-oracle-front-node
          image: wexio/so-front:latest
          imagePullPolicy: Always
          env:
            - name: VITE_REGISTRATION_API_URL
              value: 'http://127.0.0.1:8080'
            - name: VITE_PRODUCTION_API_URL
              value: 'http://127.0.0.1:8081'
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            initialDelaySeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: stage-oracle-front-service
spec:
  selector:
    app: stage-oracle-front-pod
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer