apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: so-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
      - host: so.com
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: stage-oracle-front-service
                  port:
                    number: 3000
