apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment

spec:
    replicas: 1
    selector:
        matchLabels:
          app: production-pod
          tier: backend
    template:
        metadata:
          labels:
            app: production-pod
            tier: backend
        spec:
          containers:
          - name: production-pod
            image: wexio/production-service:latest
            imagePullPolicy: Always
            env:
              - name: SPRING_DATASOURCE_URL
                value: jdbc:mysql://mysql:3306/productions?createDatabaseIfNotExist=true
              - name: SPRING_DATASOURCE_USERNAME
                value: root
              - name: SPRING_DATASOURCE_PASSWORD
                value: root
              - name: registration.service.url
                value: http://registration-service:8080
              - name: spring.mail.host
                value: mailhog

