name: build with maven

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWAN_KEY: ${{ secrets.AWAN_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build registration-service with Maven
        run: mvn -B package --file registration-service/pom.xml
      - name: Build production-service with Maven
        run: mvn -B package --file production-service/pom.xml

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKHUB_TOKEN }}

      - name: Build and push the registration-service Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./registration-service
          push: true
          tags: wexio/registration-service:latest

      - name: Build and push the production-service Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./production-service
          push: true
          tags: wexio/production-service:latest